import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from 'next/head';
import Image from "next/image";
import favicon from "../../public/favicon.png";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JKN SMARTSUPPORT | BPJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
       <Head>
          <link rel="icon" href="../../public/favicon.png" />
        </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
